import { readFileSync, readdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import type { Plugin } from 'vite';

const LOCALES = ['de', 'en', 'ar', 'cn', 'ru'] as const;
const LOCALE_INDEX: Record<string, number> = { de: 0, en: 1, ar: 2, cn: 3, ru: 4 };
const MESSAGES_DIR = join(process.cwd(), 'messages');
const OUTPUT_PATH = join(process.cwd(), 'src/lib/messages.ts');

function loadMessages(): Record<string, string[]> {
	const all: Record<string, string[]> = {};
	for (const file of readdirSync(MESSAGES_DIR).filter((f) => f.endsWith('.json'))) {
		Object.assign(all, JSON.parse(readFileSync(join(MESSAGES_DIR, file), 'utf-8')));
	}
	return all;
}

function generateCode(msgs: Record<string, string[]>): string {
	let code = `// Auto-generated by i18n-plugin. Do not edit.\n`;
	code += `export const locales = ${JSON.stringify(LOCALES)} as const;\n`;
	code += `export const cookieName = 'LOCALE';\n`;
	code += `export const cookieMaxAge = 34560000;\n\n`;

	code += `let _storage: import('node:async_hooks').AsyncLocalStorage<{ locale: string }> | null | undefined = undefined;\n\n`;

	code += `export function getLocale(): string {\n`;
	code += `  if (_storage) { const s = _storage.getStore(); if (s?.locale) return s.locale; }\n`;
	code += `  if (typeof document !== 'undefined') { const l = document.documentElement.lang; if (l) return l; }\n`;
	code += `  return 'de';\n`;
	code += `}\n\n`;

	code += `export function getLocales() { return locales; }\n\n`;

	code += `export function setLocale(locale: string): void {\n`;
	code += `  if (typeof document !== 'undefined' && (locales as readonly string[]).includes(locale)) {\n`;
	code += `    document.documentElement.lang = locale;\n`;
	code += `    document.cookie = cookieName + '=' + locale + '; path=/; max-age=' + cookieMaxAge + '; SameSite=Lax';\n`;
	code += `  }\n`;
	code += `}\n\n`;

	code += `export function getTextDirection(locale: string): string {\n`;
	code += `  return ['ar', 'he', 'fa', 'ur'].includes(locale) ? 'rtl' : 'ltr';\n`;
	code += `}\n\n`;

	code += `export function deLocalizeUrl(url: URL | string): URL {\n`;
	code += `  return typeof url === 'string' ? new URL(url) : url;\n`;
	code += `}\n\n`;

	code += `export async function runWithLocale<T>(locale: string, fn: () => T | Promise<T>): Promise<T> {\n`;
	code += `  if (_storage === undefined) {\n`;
	code += `    try {\n`;
	code += `      const { AsyncLocalStorage } = await import(/* @vite-ignore */ 'node:async_hooks');\n`;
	code += `      _storage = new AsyncLocalStorage();\n`;
	code += `    } catch {\n`;
	code += `      _storage = null;\n`;
	code += `    }\n`;
	code += `  }\n`;
	code += `  if (_storage) return _storage.run({ locale }, fn) as Promise<T>;\n`;
	code += `  return fn() as Promise<T>;\n`;
	code += `}\n\n`;

	code += `const _li: Record<string, number> = ${JSON.stringify(LOCALE_INDEX)};\n\n`;
	code += `function _t(tr: string[], p?: Record<string, string | number>): string {\n`;
	code += `  const text = tr[_li[getLocale()] ?? 0] ?? tr[0] ?? '';\n`;
	code += `  if (!p) return text;\n`;
	code += `  return text.replace(/\\{(\\w+)\\}/g, (_, k) => String(p[k] ?? '{' + k + '}'));\n`;
	code += `}\n\n`;

	for (const [key, tr] of Object.entries(msgs)) {
		code += `export function ${key}(p?: Record<string, string | number>): string { return _t(${JSON.stringify(tr)}, p); }\n`;
	}
	return code;
}

function generate(): void {
	const msgs = loadMessages();
	writeFileSync(OUTPUT_PATH, generateCode(msgs));
}

export function i18nPlugin(): Plugin {
	return {
		name: 'typed-messages',

		buildStart() {
			generate();
		},

		configureServer(server) {
			generate();
			server.watcher.add(MESSAGES_DIR);
			server.watcher.on('change', (file) => {
				if (file.startsWith(MESSAGES_DIR) && file.endsWith('.json')) {
					generate();
				}
			});
		}
	};
}
