// Auto-generated by i18n-plugin. Do not edit.
export const locales = ["de","en","ar","cn","ru"] as const;
export const cookieName = 'LOCALE';
export const cookieMaxAge = 34560000;

let _storage: import('node:async_hooks').AsyncLocalStorage<{ locale: string }> | null | undefined = undefined;

export function getLocale(): string {
  if (_storage) { const s = _storage.getStore(); if (s?.locale) return s.locale; }
  if (typeof document !== 'undefined') { const l = document.documentElement.lang; if (l) return l; }
  return 'de';
}

export function getLocales() { return locales; }

export function setLocale(locale: string): void {
  if (typeof document !== 'undefined' && (locales as readonly string[]).includes(locale)) {
    document.documentElement.lang = locale;
    document.cookie = cookieName + '=' + locale + '; path=/; max-age=' + cookieMaxAge + '; SameSite=Lax';
  }
}

export function getTextDirection(locale: string): string {
  return ['ar', 'he', 'fa', 'ur'].includes(locale) ? 'rtl' : 'ltr';
}

export function deLocalizeUrl(url: URL | string): URL {
  return typeof url === 'string' ? new URL(url) : url;
}

export async function runWithLocale<T>(locale: string, fn: () => T | Promise<T>): Promise<T> {
  if (_storage === undefined) {
    try {
      const { AsyncLocalStorage } = await import(/* @vite-ignore */ 'node:async_hooks');
      _storage = new AsyncLocalStorage();
    } catch {
      _storage = null;
    }
  }
  if (_storage) return _storage.run({ locale }, fn) as Promise<T>;
  return fn() as Promise<T>;
}

const _li: Record<string, number> = {"de":0,"en":1,"ar":2,"cn":3,"ru":4};

function _t(tr: string[], p?: Record<string, string | number>): string {
  const text = tr[_li[getLocale()] ?? 0] ?? tr[0] ?? '';
  if (!p) return text;
  return text.replace(/\{(\w+)\}/g, (_, k) => String(p[k] ?? '{' + k + '}'));
}

export function benefit1(p?: Record<string, string | number>): string { return _t(["3% Rabatt auf Kistenbestellungen","3% discount on box orders","3% خصم على طلبات الصناديق","3% 折扣","3% скидка на заказы в коробках"], p); }
export function benefit2(p?: Record<string, string | number>): string { return _t(["Versandkostenfreie Lieferung ab xx€","Free shipping over xx€","الشحن المجاني لطلبات أكثر من xx€","免费送货超过 xx€","Бесплатная доставка от xx€"], p); }
export function benefit3(p?: Record<string, string | number>): string { return _t(["Schnelle Lieferung mit DHL","Fast delivery with DHL","الشحن السريع بواسطة DHL","快速配送与 DHL","Быстрая доставка с DHL"], p); }
export function search(p?: Record<string, string | number>): string { return _t(["Suchen Sie nach Zigarren...","Search for cigars...","البحث عن سجائر...","搜索雪茄...","Поиск по сигарам..."], p); }
export function categories(p?: Record<string, string | number>): string { return _t(["Kategorien","Categories","الفئات","类别","Категории"], p); }
export function followUs(p?: Record<string, string | number>): string { return _t(["Folgen Sie uns","Follow us","تابعنا","关注我们","Следите за нами"], p); }
export function cigars(p?: Record<string, string | number>): string { return _t(["Zigarren","Cigars","السجائر","雪茄","Сигары"], p); }
export function zigarillos(p?: Record<string, string | number>): string { return _t(["Zigarillos","Zigarillos","السجائر الصغيرة","小雪茄","Сигарillos"], p); }
export function pipestobacco(p?: Record<string, string | number>): string { return _t(["Pfeifen & Tabak","Pipes & Tobacco","الأنابيب والتبغ","烟斗与烟草","Сигарные трубки и табак"], p); }
export function accessories(p?: Record<string, string | number>): string { return _t(["Zubehör","Accessories","الإكسسوارات","配件","Аксессуары"], p); }
export function spirits(p?: Record<string, string | number>): string { return _t(["Spirituosen","Spirits","المشروبات الكحولية","烈酒","Спиртные напитки"], p); }
export function gifts(p?: Record<string, string | number>): string { return _t(["Geschenkideen","Gifts","الهدايا","礼品","Подарочные идеи"], p); }
export function sale(p?: Record<string, string | number>): string { return _t(["Sale %","Sale %","الخصم %","特价","Скидки %"], p); }
export function news(p?: Record<string, string | number>): string { return _t(["News & Infos","News & Infos","الأخبار والمعلومات","新闻资讯","Новости и Информация"], p); }
export function customerService(p?: Record<string, string | number>): string { return _t(["Kundenservice","Customer Service","خدمة العملاء","客户服务","Служба поддержки"], p); }
export function aboutUs(p?: Record<string, string | number>): string { return _t(["Über uns","About Us","من نحن","关于我们","О нас"], p); }
export function contact(p?: Record<string, string | number>): string { return _t(["Kontakt","Contact","اتصل بنا","联系我们","Контакты"], p); }
export function shipping(p?: Record<string, string | number>): string { return _t(["Versand","Shipping","الشحن","配送","Доставка"], p); }
export function returns(p?: Record<string, string | number>): string { return _t(["Rückgabe","Returns","الإرجاع","退货","Возврат"], p); }
export function faq(p?: Record<string, string | number>): string { return _t(["FAQ","FAQ","الأسئلة الشائعة","常见问题","Часто задаваемые вопросы"], p); }
export function legal(p?: Record<string, string | number>): string { return _t(["Rechtliches","Legal","قانوني","法律条款","Правовая информация"], p); }
export function privacy(p?: Record<string, string | number>): string { return _t(["Datenschutz","Privacy Policy","سياسة الخصوصية","隐私政策","Политика конфиденциальности"], p); }
export function terms(p?: Record<string, string | number>): string { return _t(["AGB","Terms & Conditions","الشروط والأحكام","条款与条件","Условия использования"], p); }
export function imprint(p?: Record<string, string | number>): string { return _t(["Impressum","Imprint","البيانات القانونية","法律声明","Выходные данные"], p); }
export function newsletter(p?: Record<string, string | number>): string { return _t(["Newsletter","Newsletter","النشرة الإخبارية","邮件订阅","Рассылка"], p); }
export function newsletterDesc(p?: Record<string, string | number>): string { return _t(["Abonnieren Sie unseren Newsletter für exklusive Angebote und Neuheiten","Subscribe to our newsletter for exclusive offers and new arrivals","اشترك في نشرتنا الإخبارية للحصول على عروض حصرية ووصولات جديدة","订阅我们的邮件以获取独家优惠和新品信息","Подпишитесь на нашу рассылку для получения эксклюзивных предложений и новинок"], p); }
export function subscribe(p?: Record<string, string | number>): string { return _t(["Abonnieren","Subscribe","اشتراك","订阅","Подписаться"], p); }
export function yourEmail(p?: Record<string, string | number>): string { return _t(["Ihre E-Mail-Adresse","Your email address","عنوان بريدك الإلكتروني","您的邮箱地址","Ваш адрес электронной почты"], p); }
export function company(p?: Record<string, string | number>): string { return _t(["Unternehmen","Company","الشركة","公司","Компания"], p); }
export function paymentMethods(p?: Record<string, string | number>): string { return _t(["Zahlungsmethoden","Payment Methods","طرق الدفع","支付方式","Способы оплаты"], p); }
export function securePayment(p?: Record<string, string | number>): string { return _t(["Sichere Zahlung","Secure Payment","دفع آمن","安全支付","Безопасная оплата"], p); }
export function ageVerification(p?: Record<string, string | number>): string { return _t(["Altersverifikation erforderlich","Age Verification Required","مطلوب التحقق من العمر","需要年龄验证","Требуется подтверждение возраста"], p); }
export function ageVerificationText(p?: Record<string, string | number>): string { return _t(["Sie müssen mindestens 18 Jahre alt sein, um Tabakprodukte zu kaufen","You must be 18 or older to purchase tobacco products","يجب أن تكون 18 سنة أو أكبر لشراء منتجات التبغ","您必须年满18岁才能购买烟草产品","Вам должно быть 18 лет или больше для покупки табачных изделий"], p); }
export function copyright(p?: Record<string, string | number>): string { return _t(["Alle Rechte vorbehalten","All rights reserved","جميع الحقوق محفوظة","版权所有","Все права защищены"], p); }
export function qualityGuarantee(p?: Record<string, string | number>): string { return _t(["Premium Qualitätsgarantie","Premium Quality Guarantee","ضمان الجودة الممتازة","优质保证","Гарантия премиального качества"], p); }
export function expertCurated(p?: Record<string, string | number>): string { return _t(["Expertenauswahl","Expert Curated Selection","مختارة من قبل الخبراء","专家精选","Экспертный отбор"], p); }
export function worldwideShipping(p?: Record<string, string | number>): string { return _t(["Weltweiter Versand","Worldwide Shipping","الشحن في جميع أنحاء العالم","全球配送","Доставка по всему миру"], p); }
export function careers(p?: Record<string, string | number>): string { return _t(["Karriere","Careers","الوظائف","招聘","Карьера"], p); }
export function partners(p?: Record<string, string | number>): string { return _t(["Partner","Partners","الشركاء","合作伙伴","Партнеры"], p); }
export function cancellationRight(p?: Record<string, string | number>): string { return _t(["Widerrufsrecht","Right of Withdrawal","حق الإلغاء","撤销权","Право на отмену"], p); }
export function processing(p?: Record<string, string | number>): string { return _t(["Wird verarbeitet...","Processing...","جاري المعالجة...","处理中...","Обработка..."], p); }
export function ourAdvantages(p?: Record<string, string | number>): string { return _t(["Unsere Vorteile","Our Advantages","مزايانا","我们的优势","Наши преимущества"], p); }
export function madeInGermany(p?: Record<string, string | number>): string { return _t(["Made in Germany","Made in Germany","صنع في ألمانيا","德国制造","Сделано в Германии"], p); }
export function sslSecure(p?: Record<string, string | number>): string { return _t(["SSL Secure","SSL Secure","آمن SSL","SSL安全","SSL Безопасность"], p); }
export function companyDescription(p?: Record<string, string | number>): string { return _t(["Premium Zigarren, Zigarillos und Spirituosen für Kenner und Genießer.","Premium cigars, cigarillos and spirits for connoisseurs and enthusiasts.","سجائر وسجائر صغيرة ومشروبات كحولية فاخرة للخبراء والمتذوقين.","为鉴赏家和爱好者提供优质雪茄、小雪茄和烈酒。","Премиальные сигары, сигариллы и спиртные напитки для ценителей и энтузиастов."], p); }
export function awards(p?: Record<string, string | number>): string { return _t(["Auszeichnungen","Awards","الجوائز","奖项","Награды"], p); }
export function tastingEvents(p?: Record<string, string | number>): string { return _t(["Verkostungsevents","Tasting Events","أحداث التذوق","品鉴活动","События для проверки"], p); }
export function rumTastings(p?: Record<string, string | number>): string { return _t(["Rum-Verkostungen","Rum Tastings","تذوق الروم","朗姆酒品鉴","События для проверки спиртных напитков"], p); }
export function cigarTastings(p?: Record<string, string | number>): string { return _t(["Zigarren-Verkostungen","Cigar Tastings","تذوق السجائر","雪茄品鉴","События для проверки сигар"], p); }
export function joinOurTastings(p?: Record<string, string | number>): string { return _t(["Nehmen Sie an unseren exklusiven Verkostungen teil","Join our exclusive tasting events","انضم إلى أحداث التذوق الحصرية لدينا","参加我们的专属品鉴活动","Присоединяйтесь к нашим эксклюзивным событиям для проверки"], p); }
export function rumTastingDesc(p?: Record<string, string | number>): string { return _t(["Entdecken Sie die Welt der Premium-Rums mit unseren Experten","Discover the world of premium rums with our experts","اكتشف عالم الروم المتميز مع خبرائنا","与我们的专家一起探索优质朗姆酒的世界","Откройте для себя мир премиальных спиртных напитков с нашими экспертами"], p); }
export function cigarTastingDesc(p?: Record<string, string | number>): string { return _t(["Erleben Sie die Kunst der Zigarrenherstellung bei unseren Zigarren-Verkostungen","Experience the art of cigar making at our cigar tastings","اختبر فن صناعة السجائر في جلسات تذوق السجائر لدينا","在我们的雪茄品鉴会上体验雪茄制作艺术","Опыттесь вкус создания сигар с нашими экспертами"], p); }
export function upcomingEvents(p?: Record<string, string | number>): string { return _t(["Kommende Events","Upcoming Events","الأحداث القادمة","即将举行的活动","Предстоящие события"], p); }
export function bookNow(p?: Record<string, string | number>): string { return _t(["Jetzt buchen","Book Now","احجز الآن","立即预订","Забронировать"], p); }
export function learnMore(p?: Record<string, string | number>): string { return _t(["Mehr erfahren","Learn More","تعلم المزيد","了解更多","Узнать больше"], p); }
export function shopTitle(p?: Record<string, string | number>): string { return _t(["Unser Shop","Our Shop","متجرنا","我们的商店","Наш магазин"], p); }
export function allProducts(p?: Record<string, string | number>): string { return _t(["Alle Produkte","All Products","جميع المنتجات","所有产品","Все товары"], p); }
export function sortBy(p?: Record<string, string | number>): string { return _t(["Sortierung","Sort by","ترتيب حسب","排序","Сортировка"], p); }
export function sortNameAsc(p?: Record<string, string | number>): string { return _t(["Name A–Z","Name A–Z","الاسم أ–ي","名称 A–Z","Имя A–Z"], p); }
export function sortNameDesc(p?: Record<string, string | number>): string { return _t(["Name Z–A","Name Z–A","الاسم ي–أ","名称 Z–A","Имя Z–A"], p); }
export function sortPriceAsc(p?: Record<string, string | number>): string { return _t(["Preis aufsteigend","Price Ascending","السعر تصاعدي","价格升序","Цена по возрастанию"], p); }
export function sortPriceDesc(p?: Record<string, string | number>): string { return _t(["Preis absteigend","Price Descending","السعر تنازلي","价格降序","Цена по убыванию"], p); }
export function inStock(p?: Record<string, string | number>): string { return _t(["Auf Lager","In Stock","متوفر","有库存","В наличии"], p); }
export function outOfStock(p?: Record<string, string | number>): string { return _t(["Ausverkauft","Out of Stock","نفد المخزون","缺货","Нет в наличии"], p); }
export function addToCart(p?: Record<string, string | number>): string { return _t(["In den Warenkorb","Add to Cart","أضف إلى السلة","加入购物车","В корзину"], p); }
export function noProductsFound(p?: Record<string, string | number>): string { return _t(["Keine Produkte gefunden","No products found","لم يتم العثور على منتجات","未找到产品","Товары не найдены"], p); }
export function tools(p?: Record<string, string | number>): string { return _t(["Zubehör","Accessories","الإكسسوارات","配件","Аксессуары"], p); }
export function products(p?: Record<string, string | number>): string { return _t(["Produkte","Products","المنتجات","产品","Товары"], p); }
export function checkoutTitle(p?: Record<string, string | number>): string { return _t(["Zur Kasse","Checkout","إتمام الشراء","收银台","Оформление заказа"], p); }
export function checkoutStep1(p?: Record<string, string | number>): string { return _t(["Lieferadresse","Shipping Address","عنوان التوصيل","收货地址","Адрес доставки"], p); }
export function checkoutStep2(p?: Record<string, string | number>): string { return _t(["Zahlung & Überprüfung","Payment & Review","الدفع والمراجعة","支付与确认","Оплата и проверка"], p); }
export function checkoutShippingAddress(p?: Record<string, string | number>): string { return _t(["Lieferadresse","Shipping Address","عنوان التوصيل","收货地址","Адрес доставки"], p); }
export function checkoutBillingAddress(p?: Record<string, string | number>): string { return _t(["Rechnungsadresse","Billing Address","عنوان الفاتورة","账单地址","Платёжный адрес"], p); }
export function checkoutSameAsShipping(p?: Record<string, string | number>): string { return _t(["Rechnungsadresse entspricht Lieferadresse","Billing address same as shipping","عنوان الفاتورة نفس عنوان التوصيل","账单地址与收货地址相同","Платёжный адрес совпадает с адресом доставки"], p); }
export function checkoutSavedAddresses(p?: Record<string, string | number>): string { return _t(["Gespeicherte Adressen","Saved Addresses","العناوين المحفوظة","已保存地址","Сохранённые адреса"], p); }
export function checkoutNewAddress(p?: Record<string, string | number>): string { return _t(["Neue Adresse eingeben","Enter New Address","إدخال عنوان جديد","输入新地址","Ввести новый адрес"], p); }
export function checkoutStreet(p?: Record<string, string | number>): string { return _t(["Straße und Hausnummer","Street and house number","الشارع ورقم المنزل","街道和门牌号","Улица и номер дома"], p); }
export function checkoutPostalCode(p?: Record<string, string | number>): string { return _t(["Postleitzahl","Postal Code","الرمز البريدي","邮政编码","Почтовый индекс"], p); }
export function checkoutCity(p?: Record<string, string | number>): string { return _t(["Stadt","City","المدينة","城市","Город"], p); }
export function checkoutState(p?: Record<string, string | number>): string { return _t(["Bundesland","State","الولاية","省/州","Регион"], p); }
export function checkoutContinue(p?: Record<string, string | number>): string { return _t(["Weiter","Continue","متابعة","继续","Продолжить"], p); }
export function checkoutBack(p?: Record<string, string | number>): string { return _t(["Zurück","Back","رجوع","返回","Назад"], p); }
export function checkoutShippingMethod(p?: Record<string, string | number>): string { return _t(["Versandart","Shipping Method","طريقة الشحن","运送方式","Способ доставки"], p); }
export function checkoutStandard(p?: Record<string, string | number>): string { return _t(["Standardversand (3–5 Werktage)","Standard Shipping (3–5 business days)","الشحن العادي (3–5 أيام عمل)","标准运送（3-5个工作日）","Стандартная доставка (3–5 рабочих дней)"], p); }
export function checkoutExpress(p?: Record<string, string | number>): string { return _t(["Expressversand (1–2 Werktage)","Express Shipping (1–2 business days)","الشحن السريع (1–2 أيام عمل)","快递（1-2个工作日）","Экспресс-доставка (1–2 рабочих дня)"], p); }
export function checkoutPaymentMethod(p?: Record<string, string | number>): string { return _t(["Zahlungsart","Payment Method","طريقة الدفع","支付方式","Способ оплаты"], p); }
export function checkoutBankTransfer(p?: Record<string, string | number>): string { return _t(["Vorkasse (Banküberweisung)","Prepayment (Bank Transfer)","الدفع المسبق (تحويل بنكي)","预付款（银行转账）","Предоплата (банковский перевод)"], p); }
export function checkoutBankTransferDesc(p?: Record<string, string | number>): string { return _t(["Überweisen Sie den Betrag nach der Bestellung. Ihre Bestellung wird nach Zahlungseingang bearbeitet.","Transfer the amount after ordering. Your order will be processed upon receipt of payment.","قم بتحويل المبلغ بعد الطلب. سيتم معالجة طلبك عند استلام الدفع.","下单后转账。收到付款后将处理您的订单。","Переведите сумму после заказа. Ваш заказ будет обработан после получения оплаты."], p); }
export function checkoutNotes(p?: Record<string, string | number>): string { return _t(["Anmerkungen zur Bestellung","Order Notes","ملاحظات الطلب","订单备注","Примечания к заказу"], p); }
export function checkoutNotesPlaceholder(p?: Record<string, string | number>): string { return _t(["Besondere Wünsche oder Hinweise...","Special requests or instructions...","طلبات خاصة أو تعليمات...","特殊要求或说明...","Особые пожелания или инструкции..."], p); }
export function checkoutOrderSummary(p?: Record<string, string | number>): string { return _t(["Bestellübersicht","Order Summary","ملخص الطلب","订单摘要","Сводка заказа"], p); }
export function checkoutSubtotal(p?: Record<string, string | number>): string { return _t(["Zwischensumme","Subtotal","المجموع الفرعي","小计","Промежуточный итог"], p); }
export function checkoutFreeShipping(p?: Record<string, string | number>): string { return _t(["Kostenlos","Free","مجاني","免费","Бесплатно"], p); }
export function checkoutTotal(p?: Record<string, string | number>): string { return _t(["Gesamt","Total","الإجمالي","总计","Итого"], p); }
export function checkoutVatNote(p?: Record<string, string | number>): string { return _t(["inkl. MwSt. und Tabaksteuer","incl. VAT and tobacco tax","شاملاً ضريبة القيمة المضافة وضريبة التبغ","含增值税和烟草税","включая НДС и акциз на табак"], p); }
export function checkoutPlaceOrder(p?: Record<string, string | number>): string { return _t(["Kostenpflichtig bestellen","Place Order","تقديم الطلب","提交订单","Оформить заказ"], p); }
export function checkoutAgeError(p?: Record<string, string | number>): string { return _t(["Sie müssen mindestens 18 Jahre alt sein, um Tabakprodukte zu kaufen.","You must be at least 18 years old to purchase tobacco products.","يجب أن يكون عمرك 18 عامًا على الأقل لشراء منتجات التبغ.","您必须年满18岁才能购买烟草产品。","Вам должно быть не менее 18 лет для покупки табачных изделий."], p); }
export function checkoutStockError(p?: Record<string, string | number>): string { return _t(["Ein oder mehrere Produkte sind nicht mehr in der gewünschten Menge verfügbar.","One or more products are no longer available in the requested quantity.","منتج واحد أو أكثر لم يعد متاحاً بالكمية المطلوبة.","一个或多个商品的库存不足。","Один или несколько товаров недоступны в запрошенном количестве."], p); }
export function checkoutConfirmed(p?: Record<string, string | number>): string { return _t(["Bestellung erfolgreich aufgegeben!","Order placed successfully!","تم تقديم الطلب بنجاح!","订单提交成功！","Заказ успешно оформлен!"], p); }
export function checkoutOrderNumber(p?: Record<string, string | number>): string { return _t(["Bestellnummer","Order Number","رقم الطلب","订单号","Номер заказа"], p); }
export function checkoutEmailSent(p?: Record<string, string | number>): string { return _t(["Eine Bestätigungs-E-Mail wurde an Ihre Adresse gesendet.","A confirmation email has been sent to your address.","تم إرسال بريد إلكتروني للتأكيد إلى عنوانك.","确认邮件已发送至您的邮箱。","Письмо с подтверждением отправлено на ваш адрес."], p); }
export function checkoutBankDetails(p?: Record<string, string | number>): string { return _t(["Bankverbindung für die Überweisung","Bank Details for Transfer","تفاصيل البنك للتحويل","转账银行信息","Банковские реквизиты для перевода"], p); }
export function checkoutBankPaymentNote(p?: Record<string, string | number>): string { return _t(["Bitte überweisen Sie den Betrag innerhalb von 7 Tagen und geben Sie Ihre Bestellnummer als Verwendungszweck an.","Please transfer the amount within 7 days and include your order number as the payment reference.","يرجى تحويل المبلغ خلال 7 أيام مع الإشارة إلى رقم طلبك.","请在7天内完成转账，并在备注中注明您的订单号。","Пожалуйста, переведите сумму в течение 7 дней, указав номер заказа."], p); }
export function checkoutContinueShopping(p?: Record<string, string | number>): string { return _t(["Weiter einkaufen","Continue Shopping","مواصلة التسوق","继续购物","Продолжить покупки"], p); }
export function checkoutDeliveryTo(p?: Record<string, string | number>): string { return _t(["Lieferung an","Delivering to","التوصيل إلى","送达至","Доставка по адресу"], p); }
export function checkoutCreditCard(p?: Record<string, string | number>): string { return _t(["Kreditkarte","Credit Card","بطاقة الائتمان","信用卡","Кредитная карта"], p); }
export function checkoutCreditCardDesc(p?: Record<string, string | number>): string { return _t(["Visa, Mastercard, American Express","Visa, Mastercard, American Express","Visa, Mastercard, American Express","Visa, Mastercard, American Express","Visa, Mastercard, American Express"], p); }
export function checkoutStep3(p?: Record<string, string | number>): string { return _t(["Kartenzahlung","Card Payment","الدفع بالبطاقة","刷卡支付","Оплата картой"], p); }
export function checkoutPayNow(p?: Record<string, string | number>): string { return _t(["Jetzt bezahlen","Pay Now","ادفع الآن","立即支付","Оплатить сейчас"], p); }
export function checkoutPaying(p?: Record<string, string | number>): string { return _t(["Wird verarbeitet...","Processing...","جاري المعالجة...","处理中...","Обработка..."], p); }
export function checkoutPayError(p?: Record<string, string | number>): string { return _t(["Zahlung fehlgeschlagen. Bitte versuchen Sie es erneut.","Payment failed. Please try again.","فشل الدفع. يرجى المحاولة مرة أخرى.","支付失败，请重试。","Ошибка оплаты. Пожалуйста, попробуйте снова."], p); }
export function checkoutSelectState(p?: Record<string, string | number>): string { return _t(["Bundesland wählen","Select state","اختر الولاية","选择省/州","Выберите регион"], p); }
export function newsletterSuccess(p?: Record<string, string | number>): string { return _t(["Vielen Dank! Sie erhalten in Kürze eine Bestätigung per E-Mail.","Thank you! You will receive a confirmation email shortly.","شكراً! ستتلقى رسالة تأكيد عبر البريد الإلكتروني قريباً.","谢谢！您将很快收到一封确认邮件。","Спасибо! Вы скоро получите письмо с подтверждением."], p); }
export function careerMessageSent(p?: Record<string, string | number>): string { return _t(["Ihre Nachricht wurde erfolgreich gesendet. Wir melden uns so bald wie möglich bei Ihnen.","Your message has been sent successfully. We will get back to you as soon as possible.","تم إرسال رسالتك بنجاح. سنتواصل معك في أقرب وقت ممكن.","您的消息已成功发送。我们将尽快与您联系。","Ваше сообщение успешно отправлено. Мы свяжемся с вами как можно скорее."], p); }
export function careerMessageError(p?: Record<string, string | number>): string { return _t(["Ihre Nachricht konnte nicht gesendet werden. Bitte versuchen Sie es erneut.","Your message could not be sent. Please try again.","تعذر إرسال رسالتك. يرجى المحاولة مرة أخرى.","您的消息无法发送，请重试。","Не удалось отправить ваше сообщение. Пожалуйста, попробуйте еще раз."], p); }
export function heroTagline(p?: Record<string, string | number>): string { return _t(["Exklusiver Genuss für wahre Kenner","Exclusive Pleasure for True Connoisseurs","متعة حصرية لحقيقي الخبراء","真正鉴赏家的专属享受","Эксклюзивное удовольствие для истинных ценителей"], p); }
export function heroCtaButton(p?: Record<string, string | number>): string { return _t(["Jetzt entdecken","Discover Now","اكتشف الآن","立即探索","Открыть для себя"], p); }
